import matplotlib.pyplot as plt
import numpy as np

g_of_fat = np.array([-16,-4,20])
calories = np.array([12.5, -25, 12.5])
plot, ax = plt.subplots()
ax.scatter(g_of_fat[0], calories[0], color="red")
ax.scatter(g_of_fat[1], calories[1], color="blue")
ax.scatter(g_of_fat[2], calories[2], color="green")
ax.set_xlim(-27.5, 27.5)
ax.set_ylim(-27.5, 27.5)
ax.set_xlabel("Low Calories")
ax.set_ylabel("Low Fat")
ax.set_title("High Calories")
ax.grid(True, which = "both")
ax.axes.xaxis.set_ticklabels([])
ax.axes.yaxis.set_ticklabels([])
ax.legend(['Planet Oat', 'Chobani Oat', 'Oat Silk'])
ax2 = ax.twinx()
ax2.set_ylabel("High Fat")
ax2.set_xlabel("High Calories")
ax2.axes.xaxis.set_ticklabels([])
ax2.axes.yaxis.set_ticklabels([])
plt.show()
